- hosts: servidores
  become: true
  tasks:
      # Crea un usuario con mi nombre
    - name: "Crear usuario dparrales"
      user:
        name: dparrales
        comment: Daniel Parrales
        password: $y$j9T$F8YgbL/VS5VEpxj2KBmCH1$ceIv4m2BNGbExja2SVzftymJBrpOElfXckP90F3fiF0
        state: present
        home: /home/dparrales
        shell: /bin/bash
      # Descarga el fichero desde la url https://wordpress.org/latest.zip
    - name: "Decarga latest.zip"
      get_url:
        url: https://wordpress.org/latest.zip
        dest: /home/dparrales/latest.zip
      # Descomrpime el paquete
    - name: "Instala los paquetes necesarios"
      apt:
        pkg:
          - unzip
          - mariadb-server
          - python3-mysqldb
          - git
    - name: "Descomprime latest.zip"
      unarchive:
        remote_src: yes
        src: /home/dparrales/latest.zip
        dest: /home/dparrales/
    - name: "Crear una base de datos llamada daniel_wordpress"
      mysql_db:
        name: daniel_wordpress
        state: present
    - name: "Crear usuario llamado mysql_daniel con privilegios sobre esa base de datos"
      mysql_user:
        name: mysql_daniel
        password: asdasd
        priv: daniel_wordpress.*:ALL,GRANT
    - name: "Clonar repositorio github"
      git:
        clone: yes
        repo: 'https://github.com/josedom24/ansible_ejemplos.git'
        dest: /home/dparrales/ansible_ejemplos
